version: "3.3"
services:
  b-hunters-dirsearch:
    build: ./
    volumes:
    - ./b-hunters.ini:/etc/b-hunters/b-hunters.ini
    environment:
      - deepscan=False
      - max_threads=400
    # env_file:
    #   - ./.env